[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scripts-local"
version = "0.1.0"
description = "Local project scripts"
requires-python = ">=3.9"
dependencies = []

[tool.setuptools]
packages = ["scripts"]
